version: '2.2'

services:

  node_exporter:
    image: prom/node-exporter:v0.17.0
    container_name: node_exporter
    user: root
    privileged: true
    network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
<<<<<<< HEAD
    cpus: '0.15'
    mem_limit: 50M  
    logging:
      driver: "json-file"
      options:
        max-size: "200M"           
=======
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
    cpus: '0.15'
    mem_limit: 50M    
>>>>>>> 1d39bed13b27674ef74150cb1fcd48fa78cfa5be
    labels:
      SERVICE_TAGS: ceph-cluster

  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    privileged: true
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    command: --listen_ip="0.0.0.0" --port=18880
    restart: unless-stopped
    ports:
      - 18880:18880
<<<<<<< HEAD
    cpus: '0.15'
    mem_limit: 50M  
    logging:
      driver: "json-file"
      options:
        max-size: "200M"         
=======
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
    cpus: '0.15'
    mem_limit: 50M    
>>>>>>> 1d39bed13b27674ef74150cb1fcd48fa78cfa5be
    labels:
      SERVICE_TAGS: ceph-cluster
      
  registrator:
    container_name: registrator
    image: marksugar/registrator:v7.1
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
    - cadvisor
    - node_exporter
    environment:
    - REGISTRATOR_BIND_INTERFACE=eth0
    - NETWORK_DEVIDE=eth0 
    - NDIPSERVER_IP=172.25.250.249
    - ND_CMD=-internal=false -retry-interval=30 -resync=180
<<<<<<< HEAD
    cpus: '0.15'
    mem_limit: 50M  
    logging:
      driver: "json-file"
      options:
        max-size: "200M"    
    labels:
      SERVICE_TAGS: ceph-cluster

=======
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
    cpus: '0.15'
    mem_limit: 50M    
    labels:
      SERVICE_TAGS: ceph-cluster
>>>>>>> 1d39bed13b27674ef74150cb1fcd48fa78cfa5be

  ceph_exporter:
    container_name: ceph_exporter
    image: digitalocean/ceph_exporter:2.0.1-luminous
    network_mode: "host"
    volumes:
      - /etc/ceph:/etc/ceph
    ports:
      - 9128:9128
<<<<<<< HEAD
    cpus: '0.15'
    mem_limit: 50M  
    logging:
      driver: "json-file"
      options:
        max-size: "200M"         
    labels:
      SERVICE_TAGS: ceph-cluster
=======
    logging:
      driver: "json-file"
      options:
        max-size: "200M"
    cpus: '0.15'
    mem_limit: 50M    
    labels:
      SERVICE_TAGS: ceph-cluster
>>>>>>> 1d39bed13b27674ef74150cb1fcd48fa78cfa5be
