global:
  slack_api_url: 'https://hooks.slack.com/services/<ID>'
route:
    receiver: 'slack'
#    group_by: [alertname,]
receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    username: 'Prometheus'
    channel: '# < SLACK >'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: '{{ template "slack.my.title" . }}'
    text: '{{ template "slack.my.text" . }}'
templates:
- 'my.tepl'
